### ISSUE TITLE
High memory usage with playerctl module

### ISSUE THREAD

**Issue by TorchedSammy** [Nooo37/bling#24]
After moving to arch and also using the playerctl module to show music now playing I noticed that there was *very* high memory usage (awesome using 60% of my 4gb ram overnight)

Disabling the playerctl module reduced the overnight growth but it was still 14% which it should not be near.

**Comment by JavaCafe01** [comment]
@TorchedSammy I've never had a high memory usage with AwesomeWM (master branch) when having bling installed and with `playerctl` enabled (around 350 MB with no windows open), and @Nooo37 tried it out with AwesomeWM stable with similar results. Maybe there is something going on in your config? If you wouldn't mind, you can send a link to your full config here and I can take a look at it.

**Comment by TorchedSammy** [comment]
https://www.github.com/TorchedSammy/dotfiles/tree/master/config/awesome

I also used awesome stable and bling playerctl module while on alpine and my memory usage was really low (2%)

**Comment by Nooo37** [comment]
The problem is reproducable with that config on stable. I've seen a 0.5% memory usage increase over 15 minutes which is enough to accumulate to higher amounts over time. While tweaking around with the garbagecollector settings can diminish the problem, the effect doesn't fully disappear. Maybe we should try adding a garabgecollector call as an exit callback like proposed here in a related issue: https://github.com/awesomeWM/awesome/issues/1490

**Comment by JavaCafe01** [comment]
I can take a look at that issue later this week. @TorchedSammy, for now, you can probably tweak your GC settings to accommodate for the leaks. I have this in my `rc.lua` and I haven't gotten spikes so far:

```lua
collectgarbage("setpause", 110)
collectgarbage("setstepmul", 1000)
```

**Comment by JavaCafe01** [comment]
@Nooo37 I'm new to this stuff, but if I remember correctly you told me over discord that your cpu percentage was high with the playerctl signal enabled. That's supposed to happen right? That means your GC is working aggressively. Unless there were actual spikes and it was increasing over time?

**Comment by JavaCafe01** [comment]
So I did some more investigation. It seems that there are memory leaks, but I believe it is due to Lua, not the module or AwesomeWM. Here is some of my data:

![noGC_playerctl_enabled](https://user-images.githubusercontent.com/33443763/110788376-63841980-8223-11eb-8f88-6cb5ce0356e1.png)

The above image is the `awesome` process running with bling's playerctl module without *any* garbage collector modifications.

![noGC_playerctl_disabled](https://user-images.githubusercontent.com/33443763/110788520-962e1200-8223-11eb-822b-2417b2247548.png)

The above image is the process with the module disabled. This is the ideal usage.

![GC_playerctl_disabled](https://user-images.githubusercontent.com/33443763/110788825-fa50d600-8223-11eb-81ba-a59d84add3de.png)

The above image has more aggressive GC options without playerctl enabled:
```lua
collectgarbage("setpause", 110)
collectgarbage("setstepmul", 1000)
```
This is a little bit better than the ideal usage, but might be cpu intensive.

![noGC_playerctl_enabled_collect](https://user-images.githubusercontent.com/33443763/110789042-4ac83380-8224-11eb-9799-f9c1729c2a62.png)

The above image is with the playerctl module enabled with `collectgarbage("collect")` calls in the nested async shell function of the module. Even though this does not have the aggressive options enabled, it is much better than the first plot.

![oof](https://user-images.githubusercontent.com/33443763/110789565-de016900-8224-11eb-9cf8-3a5e39a0f115.png)

The above image is the module with the `collectgarbage("collect")` calls and the aggressive options. It is a little bit better than the one right above.

### Conclusion

I don't think that we can achieve the flat curve with the playerctl module, we can only smooth it out with the GC options. So the best way to handle this is to add the more aggressive options and the GC collect call to smooth the curve down. Also, a disable method for the playerctl mixed into widgets can improve performance as well.

**Comment by JavaCafe01** [comment]
Actually, the graph is stepping, so I might of missed a collect garbage call somewhere

**Comment by JavaCafe01** [comment]
Improved with #26
